# Generated by Django 4.1 on 2022-09-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tweet_delete_departments_delete_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
